Make tonic-prometheus-layer compatible with latest tonic v0.12
An incompatibility was introduced in this commit:
https://github.com/hyperium/tonic/commit/9c1f2f9402d97cfa4c9d9065b5af2fb99d2ef521
wherein the type inside the Response of the Service trait was changed:

-        type Response = hyper::Response<Body>;
+        type Response = hyper::Response<tonic::body::BoxBody>;

leading to this error:

error[E0277]: the trait bound `MetricsService<Routes>: tower::Service<hyper::Request<UnsyncBoxBody<hyper::body::Bytes, Status>>>` is not satisfied

We do not care about the body inside the request at all, so just make it
a parameter so that we are compatible with anything.